### ISSUE TITLE
[1.19] Forge breaking changes

### ISSUE THREAD

**Issue by Baggytrousers27** [Sarinsa/QuickCure#1]
Forges 41.0.64+ and 41.0.94+ introduce breaking changes for QuickCure-1.19-5.0.0.

**Comment by Sarinsa** [comment]
Frick

**Comment by Baggytrousers27** [comment]
That made me laugh far harder than it should've and choke on my own saliva.
Cheers. ¦D

**Comment by Sarinsa** [comment]
Amazing

**Comment by Sarinsa** [comment]
Taken care of!
