### ISSUE TITLE
I ported to 1.20+ on fabric.

### ISSUE THREAD

**Issue by Logboy2000** [Sarinsa/QuickCure#2]
Am i allowed to host it on Modrinth. If not I would be happy if you could add it to your page. Thanks!
https://github.com/Logboy2000/QuickCure-Fabric-1.20-Port

**Comment by Sarinsa** [comment]
Yeah, go for it man :)

**Comment by Logboy2000** [comment]
> Yeah, go for it man :)

Thanks bro

**Comment by Logboy2000** [comment]
currently under review. will be up at this link soon: https://modrinth.com/mod/quick-cure-fabric

![image](https://github.com/Sarinsa/QuickCure/assets/72185335/7c76de4c-af6f-49fb-834e-bdb61cf3f720)
